swagger: '2.0'
info:
  title: api-gateway
  description: API Gateway
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
x-google-management:
  metrics:
    - name: pytest-smoothies-request
      displayName: pytest smoothie quota
      valueType: INT64
      metricKind: DELTA
  quota:
    limits:
      - name: pytest-smoothie-limit
        metric: pytest-smoothies-request
        unit: 1/min/{project}
        values:
          STANDARD: 60

paths:
  /pytest:
    get:
      summary: Run PyTest
      operationId: pytest-v1
      security:
        - api_key: []
      x-google-quota:
        metricCosts:
          pytest-smoothies-request: 1
      x-google-backend:
        address: {{URL}}
      consumes:
        - application/json
      produces:
        - application/json        
      responses:
        '200':
          description: OK


securityDefinitions:
  api_key:
    type: apiKey
    name: key
    in: query